site_name: Az Én Blogom / Dokumentációm
site_url: https://pzs70.github.io/MkDocsTest/

theme:
  name: readthedocs
  language: hu
  palette:
    primary: indigo
    accent: indigo

nav:
  - Főoldal: index.md