site_name: Az Én Blogom / Dokumentációm
site_url: https://pzs70.github.io/MkDocsTest/

theme:
  name: material
  language: hu
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.tabs.sticky
#nav:
#  - Főoldal: index.md
#  - Második oldal: second.md
